// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UserWithRolesMvc.Data;

#nullable disable

namespace UserWithRolesMvc.Migrations
{
    [DbContext(typeof(UserDbContext))]
    [Migration("20250624172741_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("UserWithRolesMvc.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Akib",
                            LastName = "Rahman",
                            Role = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "Riyadh",
                            LastName = "Khan",
                            Role = "Salesman"
                        },
                        new
                        {
                            Id = 3,
                            FirstName = "Taslima",
                            LastName = "Akter",
                            Role = "Manager"
                        },
                        new
                        {
                            Id = 4,
                            FirstName = "Jamal",
                            LastName = "Uddin",
                            Role = "Salesman"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
